# Generated by Django 5.1.7 on 2025-05-26 21:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('organizations', '0004_car_facility_wastecontainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
