# Generated by Django 5.1.7 on 2025-05-26 22:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_organizationjoincode'),
        ('operations', '0002_team_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Driver', 'Driver'), ('TeamLeader', 'Team Leader'), ('Collector', 'Collector')], max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='human_resources.employment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='operations.team')),
            ],
            options={
                'unique_together': {('employment', 'team', 'removed_at')},
            },
        ),
    ]
