# Generated by Django 5.1.7 on 2025-05-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_shiftmodel_shiftprogressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftmodel',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
