# Generated by Django 5.1.7 on 2025-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('organization_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private')], max_length=20)),
                ('num_of_facilities', models.IntegerField()),
                ('num_of_cars', models.IntegerField()),
                ('num_of_containers', models.IntegerField()),
            ],
        ),
    ]
