# Generated by Django 5.1.7 on 2025-04-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_num_of_cars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=50, unique=True)),
                ('car_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('recycling', 'Recycling'), ('treatment', 'Waste Treatment')], max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('capacity', models.IntegerField()),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WasteContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=50, unique=True)),
                ('container_type', models.CharField(choices=[('bin', 'Bin'), ('dumpster', 'Dumpster')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_containers', to='organizations.organization')),
            ],
        ),
    ]
